export const TOOL_LABELS: Record<string, string> = {
    run_accessibility_audit: 'Running accessibility audit',
    analyze_visual_design: 'Analyzing visual design',
    check_dom_quality: 'Checking DOM quality',
    run_contrast_check: 'Checking color contrast',
    check_seo: 'Checking SEO',
    analyze_forms: 'Analyzing forms',
    get_performance_metrics: 'Getting performance metrics',
    get_page_structure: 'Analyzing page structure',
    click_element: 'Clicking element',
    fill_input: 'Filling form field',
    scroll_to_element: 'Scrolling to element',
    scroll_page: 'Scrolling page',
    highlight_elements: 'Highlighting elements',
    clear_highlights: 'Clearing highlights',
    take_screenshot: 'Taking screenshot',
    navigate_to_url: 'Navigating to website',
    open_new_tab: 'Opening new tab',
    switch_tab: 'Switching tab',
    get_open_tabs: 'Listing open tabs',
    get_page_links: 'Getting page links',
    get_current_url: 'Getting current URL',
    run_specialized_task: 'Running specialized task',
    run_parallel_tasks: 'Running parallel tasks',
    ask_user: 'Asking user',
    generate_report: 'Generating report',
    list_reports: 'Listing reports',
    create_group: 'Creating task group',
    create_tasks_batch: 'Creating tasks',
    list_groups: 'Listing task groups',
    delete_group: 'Deleting task group',
    list_tasks: 'Listing tasks',
    update_task: 'Updating task',
    delete_task: 'Deleting task',
}

export const SUBAGENT_TOOLS = new Set(['run_specialized_task', 'run_parallel_tasks'])
